-- Team members + properties seed. Import after schema.sql via phpMyAdmin.

INSERT INTO team_members (name, role, photo, bio, is_ceo, sort_order) VALUES ('Olopade Yetunde', 'Chief Executive Officer', 'images/team/yetunde.jpg', 'A seasoned expert in events marketing, sponsorship activation, and brand partnerships with over 20 years of experience. Yetunde specialises in large-scale sports events, corporate collaborations, and impactful brand engagements — driving Nilayo\'s strategic vision and setting industry benchmarks in sports marketing across Africa.', 1, 0);
INSERT INTO team_members (name, role, photo, bio, is_ceo, sort_order) VALUES ('Olopade Adenike', 'Chief Operating Officer', 'images/team/adenike.jpg', 'The operational architect behind NSML\'s growth. Adenike ensures that every sponsorship commitment, event logistics plan, and client relationship is executed to the highest standard. She brings the same precision to a community 10KM race as to a World Athletics-certified marathon — because NSML\'s reputation is built on delivery, every single time.', 0, 1);
INSERT INTO team_members (name, role, photo, bio, is_ceo, sort_order) VALUES ('Odeh Emmanuel', 'Project Lead', 'images/team/emmanuel.jpg', 'A results-driven professional with expertise in business development, entrepreneurship, and team leadership. With extensive experience in project execution, Emmanuel drives business growth and operational efficiency. Backed by certifications in Business Administration and Management, his strategic vision and hands-on leadership make him a key asset in project management and business development at Nilayo.', 0, 2);
INSERT INTO team_members (name, role, photo, bio, is_ceo, sort_order) VALUES ('Adekite Bolaji', 'Admin', 'images/team/bolaji.jpg', 'An experienced HR professional with a BA in English Language, an MBA, and multiple professional certifications. Bolaji specialises in talent management, employee relations, and organisational development — nurturing a dynamic work environment. Committed to excellence and innovation, she drives Nilayo Sports\' success by attracting and developing top talent.', 0, 3);
INSERT INTO team_members (name, role, photo, bio, is_ceo, sort_order) VALUES ('Odi Jide', 'Brand & Comms Lead', 'images/team/jide.jpg', 'A seasoned media and communications professional with expertise in broadcast journalism, brand strategy, creative advertising, and media production. With over a decade of experience, Jide blends analytical insight with creative storytelling to strengthen Nilayo\'s brand presence. A trained journalist from the Nigerian Institute of Journalism and an alumnus of O2 Academy Lagos, he plays a key role in shaping the company\'s communication and marketing strategies.', 0, 4);
INSERT INTO team_members (name, role, photo, bio, is_ceo, sort_order) VALUES ('Omoniyi Sandra', 'Business Strategist', 'images/team/sandra.jpg', 'A specialist in sports management, strategy, and operations with a Master\'s in Sport Management and Administration and over a decade of experience. Sandra develops strategic solutions that drive revenue and brand growth, excels in forging high-impact partnerships, and creates sustainable business models that elevate sports properties. She combines strategic insight with deep industry expertise to deliver innovative solutions for brands and stakeholders.', 0, 5);

INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'lagos-marathon', 'Access Bank Lagos City Marathon', 'Flagship Property', 'World Athletics', 'images/events/lagos/lagos-card.jpg', 'images/events/ablcm-logo-[no-year].png', 'Africa\'s Strongest Marathon Brand 2025 — a World Athletics Global Certification. The 10th anniversary edition delivered in 2025 drew participation from across the globe, backed by Access Bank, KIA Motors, Seven Up, Aquafina, and Airtel. Raises over ₦3 billion annually from the private sector since its inception in 2016.', '440K+', 'Participants since 2016', '₦3B+', 'Raised annually', 'Feb 2027', 'Next edition', 'lagos-marathon.html', 1, 0, 0
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'abuja-marathon', 'PremiumTrust Bank Abuja City International Half Marathon', 'International', NULL, 'images/events/abuja-hero.jpg', 'images/events/abj-logo-new.png', 'The capital\'s premier long-distance race. Inaugural edition April 2024 with 50,000+ participants. Backed by PremiumTrust Bank, Dana Airlines, Seven Up, Aquafina, and the AFN.', '50K+', 'Participants', 'Nov 2026', 'Next edition', NULL, NULL, 'abuja-marathon.html', 0, 0, 1
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'abeokuta-race', 'Abeokuta 10KM Race', 'Heritage Race', NULL, 'images/events/abeokuta-hero.jpg', 'images/events/abk-logo.png', 'A race rich in cultural significance since 2019. Long-term commitments from Lotus Bank, Access Bank, Rite Foods, JAC Motors, Airtel, Trophy, Lafarge, and more.', '120K+', 'Participants', 'Sept 2025', 'Next edition', NULL, NULL, 'abeokuta-race.html', 0, 0, 2
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'enugu-marathon', 'Enugu City International Marathon', 'New Property', NULL, 'images/events/enugu-hero.jpg', 'images/events/enugu-marathon-logo.png', 'Maiden edition May 2025 with 13,000+ runners. Backed by Pinnacle Oil, Air Peace, World Athletics, Three Crowns, RC Cola, and the Athletics Federation of Nigeria.', '13K+', 'Debut runners', '2026', 'Next edition', NULL, NULL, 'enugu-marathon.html', 0, 0, 3
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'yenagoa-race', 'Yenagoa City International 10KM Race', 'New Property', NULL, 'images/events/yenagoa-hero.jpg', 'images/events/yc1km.png', 'First World Athletics-supervised race in Southern Nigeria. Inaugural edition 2026 with 5,000+ runners. Backed by Bayelsa State Government and strategic partners.', '5K+', 'Debut runners', '2027', 'Next edition', NULL, NULL, 'yenagoa-race.html', 0, 0, 4
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'stormers-club', 'Stormers Sports Club', 'Sports Club', NULL, 'images/events/stormers-hero.jpg', 'images/events/stormers-logo.png', 'Back-to-back Lisabi Cup Champions 2024 and 2025. Academy built from Baptist Boys High School talent under long-term contracts. Senior team newly promoted to Nigeria\'s NNL.', '2x', 'Lisabi Champions', 'NNL', 'Promoted', NULL, NULL, 'stormers-club.html', 0, 0, 5
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'ijebu-marathon', 'Ijebu Heritage Half Marathon', 'Heritage Race', NULL, 'images/events/ijebu-hero.jpg', 'images/events/aihhm-2023-logo.png', 'A race steeped in cultural significance, delivered in collaboration with Airtel Nigeria. Maiden edition held 17 July 2021 with 5,000+ runners and spectators.', '5K+', 'Participants', '2021', 'Maiden edition', NULL, NULL, 'ijebu-marathon.html', 0, 0, 6
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'kaduna-marathon', 'Kaduna Half Marathon', 'Northern Nigeria', NULL, 'images/events/kaduna/kaduna-04.jpg', 'images/events/kaduna-marathon-logo.png', 'A 21.1km road race that made history as the first World Athletics-supervised marathon event in Northern Nigeria. The inaugural 2021 edition drew over 7,000 runners to the streets of Kaduna.', '7K+', 'Runners — inaugural edition', '21.1 KM', 'Race distance', '2021', 'Inaugural edition', 'kaduna-marathon.html', 0, 0, 7
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'iau-remo-championship', 'IAU African Championship Remo', 'International · Ultra-Distance', NULL, 'images/events/remo/remo-03.jpg', 'images/events/iau-remo-logo.png', 'International ultra-distance running came to Remo, Ogun State, for its inaugural 2019 edition. Sanctioned by the International Association of Ultrarunners (IAU), it drew over 5,000 participants and spectators.', '5K+', 'Participants — inaugural edition', 'Ultra', 'Distance championship', '2019', 'Inaugural edition', 'iau-remo-championship.html', 0, 0, 8
);
INSERT INTO properties (slug, title, tag, badge, hero_image, logo_image, description, stat1_val, stat1_lbl, stat2_val, stat2_lbl, stat3_val, stat3_lbl, detail_url, is_featured, is_upcoming, sort_order) VALUES (
  'copa-lagos', 'Copa Lagos Beach Soccer', NULL, 'Upcoming · Dec 2026', 'images/events/copa-lagos-hero.jpg', 'images/events/copa-lagos_web.png', 'Nigeria\'s premier beach football and lifestyle event returns to Eko Atlantic City. A three-day high-energy weekend drawing 20,000+ fans, athletes, and lifestyle enthusiasts. Licensee granted by Kinetic Sports — first return since the 2019 edition.', NULL, NULL, NULL, NULL, NULL, NULL, 'copa-lagos.html', 0, 1, 0
);
